[package]
name = "celeste"
version = "0.1.6"
edition = "2021"

[dependencies]
adw = { package = "libadwaita", version = "0.2.1", features = ["v1_2"] }
base64 = "0.20.0"
blocking = "1.3.0"
clap = { version = "4.0.12", features = ["derive", "env"] }
dirs = "4.0.0"
exitcode = "1.1.2"
file-lock = "2.1.6"
glob = "0.3.0"
hw-msg = "0.3.1"
indexmap = "1.9.2"
futures = "0.3.25"
librclone = { version = "0.3.0" }
quit = "1.1.4"
rand = "0.8.5"
regex = "1.6.0"
sea-orm = { version = "0.10.3", features = ["sqlx-sqlite", "runtime-async-std-rustls", "macros"] }
sea-orm-migration = "0.10.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
time = { version = "0.3.17", features = ["serde-well-known"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "sync"] }
toml_edit = { version = "0.14.4", features = ["serde"] }
url = "2.3.1"
users = "0.11.0"

[build-dependencies]
grass = "0.11.2"
